### ISSUE TITLE
error: Untyped global name 'imread': Cannot determine Numba type of <class 'function'>

### ISSUE THREAD

**Issue by acsr** [tdh8316/triangler#12]
Setup on macOS Ventura Apple Silicon, Python 3.11.5 venv (manually created)
installed in isolated venv using command:

```shell
python -m pip install git+https://github.com/tdh8316/triangler/
```

Error with PNG and JPEG:

```
python -m triangler -v apples.jpg   
[2024-03-13 12:50:15][INFO] in main(): Options:Namespace(images=['apples.jpg'], output=None, sample='THRESHOLD', edge='SOBEL', blur=2, color='CENTROID', points=1024, reduce=False, verbose=True)
Converting /Users/astro/github/Triangler/apples.jpg...
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/astro/github/Triangler/lib/python3.11/site-packages/triangler/mod.py", line 89, in convert_and_save
    im = Image.fromarray(self.convert(source).astype(np.uint8))
                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/astro/github/Triangler/lib/python3.11/site-packages/triangler/mod.py", line 58, in convert
    return process(
           ^^^^^^^^
  File "/Users/astro/github/Triangler/lib/python3.11/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/astro/github/Triangler/lib/python3.11/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: Literal propagation)
Failed in literal_propagation_subpipeline mode pipeline (step: performs partial type inference)
Untyped global name 'imread': Cannot determine Numba type of <class 'function'>

File "lib/python3.11/site-packages/triangler/process.py", line 30:
def process(
    <source elided>
    if isinstance(img, str):
        img = imread(img)
        ^
```

pip freeze output:

```
imageio==2.34.0
lazy_loader==0.3
llvmlite==0.42.0
networkx==3.2.1
numba==0.59.0
numpy==1.26.4
packaging==24.0
pillow==10.2.0
scikit-image==0.22.0
scipy==1.12.0
tifffile==2024.2.12
triangler @ git+https://github.com/tdh8316/triangler/@789b280a9c4fb7a593122d2dff783c82e509965f
```

**Comment by tdh8316** [comment]
Hi, thank you for reporting the issue on Apple Silicon macOS.

Unfortunately, I'm overwhelmed with work for now. So I can look it over on the weekend.

Sorry for the delay!

Best regards,

**Comment by tdh8316** [comment]
Hi, I'm sorry for the delay.

I rewrote the whole codebase since it was too old! I released this code 5 years ago and did not update it.

Just so you know, I tested this new version on my MacBook Pro 14 with M2, macOS 14.3 Sonoma.

Best regards!
